SQL - Add LIMIT 1 with ORDER BY distance  when intersecting point and parcelle
3liz/qgis-gestion_base_adresse-plugin pull request #145
Opened 2021-12-16 15:58 UTC by Gustry

* SQL - Add LIMIT 1 with ORDER BY distance  when intersecting point and parcelle

Manque le cas si il n'y a pas de parcelle sous le point adresse en question. Ou alors considère-t-on ca un problème dans les données ?

2021-12-16 18:15 UTC, mdouchin requested changes
I think it would be better to use a left join instead of a subquery. Let's talk about it tomorrow

2021-12-20 15:53 UTC, Gustry commented
This fix allows NULL values and will take the first polygon containing the point (if many polygons overlap).

2021-12-21 10:30 UTC, rldhont approved these changes

2021-12-21 10:30 UTC, rldhont commented on gestion_base_adresse/processing/data/data_parcelle.py
> +            WHERE ST_Contains(p.geom, pa.geom)
```suggestion
            WHERE ST_Contains(p.geom, pa.geom) LIMIT 1
```
Même si a priori les parcelles ne se superposent pas, on ne sait jamais.

2021-12-21 11:30 UTC, Gustry commented on gestion_base_adresse/processing/data/data_parcelle.py
> +            WHERE ST_Contains(p.geom, pa.geom)
On ne peut pas ajouter un `LIMIT` sur ce genre de requête. Ce n'est pas une sous-requête.
J'avais testé hier justement dans mon commentaire. PostGIS prend le dernier polygone.

2021-12-21 12:05 UTC, drillinP approved these changes

2021-12-21 12:34 UTC, rldhont commented on gestion_base_adresse/processing/data/data_parcelle.py
> +            WHERE ST_Contains(p.geom, pa.geom)
Désolé j'avais mal lu la différence de code.

2021-12-21 12:34 UTC, rldhont approved these changes

2021-12-21 12:36 UTC, rldhont commented
@mdouchin: @Gustry has made changes since your review, can you check the enchantements ?

2021-12-21 14:05 UTC, mdouchin approved these changes

2021-12-21 14:37 UTC, merged