Commune déléguée
3liz/qgis-gestion_base_adresse-plugin pull request #147
Opened 2021-12-22 09:56 UTC by Gustry

Support client

> Fournir une fonction pour remplir la table referencer_com. Cette table sert de table pivot entre communes et communes_deleguee. Une commune_deleguee est incluse dans une commune, donc un simple st_intersects entre le centroid de la géométrie de la commune_deleguee et la géométrie de la commune devrait suffire.

À faire par la main par les utilisateurs pour le moment : `SELECT reset_referencer_com();`

> Modifier la vue export_bal pour tenir compte du fait qu'il y a plusieurs communes_deleguee par commune donc ajouter à la jointure de commune_deleguee un st_intersects entre le point adresse et la commune_deleguee: nouvelle version du plugin !

À vérifier ...

2021-12-22 10:06 UTC, Gustry commented on gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql
> +TRUNCATE adresse.referencer_com RESTART IDENTITY;
Nous devons enlever. Il y a des attributs en plus sur la table pivot, comme des "actions".

2021-12-22 10:12 UTC, mdouchin requested changes

2021-12-22 10:12 UTC, mdouchin commented on docs/extension-qgis/user-guide.md
> +Nous, on s'occupera uniquement des sections **Couches** et **Éditions de couche**, pour le reste en ce qui
Profiter de ce PR pour remplacer ce type de syntaxe "Nous, blabla" par un simple "On s'occupera ..."

2021-12-22 10:12 UTC, mdouchin commented on gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql
> +TRUNCATE adresse.referencer_com RESTART IDENTITY;
We should not use a `TRUNCATE` if we do not want to erase the existing data.

We could check if there is a unique constraint on the couple id_com, id_com_deleguee (and/or action if we can have more than one line referencing 2 cities ?). If not, create it and use it for a 

```sql
ON CONFLICT ON CONSTRAINT name_of_the_unique_constraint 
DO NOTHING;
```

2021-12-22 10:12 UTC, mdouchin commented on gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql
> +	cd.id_com_del AS id_com_del
Should we insert data for the 2 other columns `action` and `date_action` ?

2021-12-22 10:12 UTC, mdouchin commented on gestion_base_adresse/install/sql/adresse/10_FUNCTION.sql
> +TRUNCATE adresse.referencer_com RESTART IDENTITY;
Or we could add a parameter to the function, `"do_truncate" boolean` to let the user decide if we should truncate first or not ?

2021-12-23 09:13 UTC, rldhont commented on gestion_base_adresse/install/sql/adresse/30_VIEW.sql
> +     LEFT JOIN adresse.commune_deleguee cd ON (((cd.id_com_del = rc.id_com_deleguee) AND public.st_contains(cd.geom, p.geom))))
Est-il possible d'éviter le `public` ?

2022-01-05 17:46 UTC, Gustry commented on gestion_base_adresse/install/sql/adresse/30_VIEW.sql
> +     LEFT JOIN adresse.commune_deleguee cd ON (((cd.id_com_del = rc.id_com_deleguee) AND public.st_contains(cd.geom, p.geom))))
Ce fichier est généré automatiquement **avec** public. Il n'est possible pour le moment. Cela est le même dans VVV, openads ou autres extensions avec BDD.

2022-01-06 15:26 UTC, Gustry commented
@mdouchin I have removed the `TRUNCATE` and used the `ON CONFLICT DO NOTHING`.

But IMHO, this function won't be used that much, it's not exposed in the UI for now. The customer has already runned the query for now.

Ok for merging ?

I can make a follow-up PR for the documentation update

2022-01-31 14:36 UTC, merged