Certificat num
3liz/qgis-gestion_base_adresse-plugin pull request #69
Opened 2020-09-03 07:49 UTC by drillinP

Partie concernant les certificats de numérotation. Script qui initialise la table adresse.parcelle et créer toutes les vues nécessaires.

2020-09-10 13:18 UTC, drillinP commented
Review Needed

2020-09-11 09:41 UTC, Gustry commented on gestion_base_adresse/install/sql/upgrade/upgrade_to_0.2.2.sql
> -BEGIN;
Même question

2020-09-11 09:41 UTC, Gustry commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
Il y a une typo dans le nom du fichier

2020-09-11 09:54 UTC, drillinP commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
C'est à dire une typo ?

2020-09-11 09:55 UTC, Gustry commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
Une typographie, une faute de frappe

2020-09-11 10:02 UTC, drillinP commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
'certificat' est bien écrit et 'numérotation' aussi

2020-09-11 10:02 UTC, drillinP commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
a je voie le 'é' ?

2020-09-11 10:07 UTC, Gustry commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
`cartificat`

2020-09-11 10:08 UTC, drillinP commented on gestion_base_adresse/resources/composer/cartificat_numérotation.qpt
> +<Layout units="mm" printResolution="300" name="Certificat de numérotation" worldFileMap="{b2fb99e3-b452-4844-bece-ede637bda8a3}">
au debut je regarder le name=  :(

2020-09-17 07:21 UTC, Gustry commented on gestion_base_adresse/processing/data/data_parcelle.py
> +        return {self.OUTPUT_MSG: msg, self.OUTPUT: output_layers}
Les variables `msg` et `output_layers` semblent être vides à la fin du traitement, non?

2020-09-21 07:26 UTC, rldhont requested changes

2020-09-21 07:26 UTC, rldhont commented on gestion_base_adresse/processing/data/data_parcelle.py
> +        return {self.OUTPUT_MSG: msg, self.OUTPUT: output_layers}
Je confirme

2020-09-21 09:13 UTC, rldhont approved these changes

2020-09-21 09:19 UTC, drillinP commented
@rldhont  rebase and merge ?

2020-09-21 09:23 UTC, merged