Update script data_parcelle
3liz/qgis-gestion_base_adresse-plugin pull request #88
Opened 2020-12-15 16:12 UTC by drillinP

* Ticket : #87 
* Mise à jour de l'algorithme data_parcelle.py:
  * Choix de remplir ou non la table adresse.parcelle
  * Changement du préfixe des vues concernées pas ce script

2020-12-16 08:21 UTC, rldhont commented
Peux-tu ajouter des tests ?

2020-12-17 13:37 UTC, rldhont requested changes
tests needed

2020-12-17 17:45 UTC, drillinP commented
> tests needed

@rldhont Pour ajouter un test ici il nous faut des données cadastrale comme le génère le plugin cadastre car certaines vues utilisent les tables cadastre pour se créer

2020-12-18 09:05 UTC, rldhont approved these changes
Ok test trop dur à mettre en place

2020-12-18 11:25 UTC, merged